### PR TITLE
Require GAP >= 4.11

### LINKED ISSUE #31: installation problem
I have tried to install the released version of the package (0.1) with GAP 4.10.2,
which should work, according to the dependencies in `PackageInfo.g`.
I got the following error messages.

```
  CC       src/meataxe64_la-meataxe64.lo
src/meataxe64.c: In function ‘FuncMTX64_Make8BitConversion’:
src/meataxe64.c:689:59: error: macro "FFE_FELT_FIELDINFO_8BIT" passed 2 arguments, but takes just 1
       FFV ent2 = VAL_FFE(FFE_FELT_FIELDINFO_8BIT(info,ent));
                                                           ^
In file included from /users/sam/gap/gap-4.10.2/src/compiled.h:30:0,
                 from src/meataxe64.h:5,
                 from src/meataxe64.c:12:
src/meataxe64.c:689:26: error: ‘FFE_FELT_FIELDINFO_8BIT’ undeclared (first use in this function)
       FFV ent2 = VAL_FFE(FFE_FELT_FIELDINFO_8BIT(info,ent));
                          ^
```

The same happens when I try to install the master branch of the package with GAP 4.10.2.

(The installation of the master branch version of the package with the master branch of GAP works.
Is the package meataxe64 really expected to work with GAP 4.10?)

P.S.:
The installation instructions in `README.md` should say `with-gaproot` not `with-gap-root`.

### PR DESCRIPTION
**Pull request by fingolfin**
Several of its features are used by meataxe64

### CODE REVIEW

**Comment by fingolfin** [comment]
@stevelinton all those test failures already exist on the master branch, I am afraid.

**Comment by stevelinton** [comment]
I think I know what it is. It is actually a compiler bug (in gcc up to version 7.4) but I have a workaround in the MTX64 standalone.

**Comment by fingolfin** [comment]
@stevelinton please let me know once you have a fix in the repository, then I can rebase my PRs.

**Comment by stevelinton** [comment]
I put in the fix,  but it is still segfaulting with clang 7.0.0 on some of the tests. The closet version I have is version 7.1 which seems to work. Version 6 fails to compile the assembler  code.

**Comment by fingolfin** [comment]
I rebased this and my other PRs, and updated issue #35 with the details provided by @stevelinton plus some suggestions of mine.

Perhaps the three PRs could be merged now?
