### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/meataxe64#31]
I have tried to install the released version of the package (0.1) with GAP 4.10.2,
which should work, according to the dependencies in `PackageInfo.g`.
I got the following error messages.

```
  CC       src/meataxe64_la-meataxe64.lo
src/meataxe64.c: In function ‘FuncMTX64_Make8BitConversion’:
src/meataxe64.c:689:59: error: macro "FFE_FELT_FIELDINFO_8BIT" passed 2 arguments, but takes just 1
       FFV ent2 = VAL_FFE(FFE_FELT_FIELDINFO_8BIT(info,ent));
                                                           ^
In file included from /users/sam/gap/gap-4.10.2/src/compiled.h:30:0,
                 from src/meataxe64.h:5,
                 from src/meataxe64.c:12:
src/meataxe64.c:689:26: error: ‘FFE_FELT_FIELDINFO_8BIT’ undeclared (first use in this function)
       FFV ent2 = VAL_FFE(FFE_FELT_FIELDINFO_8BIT(info,ent));
                          ^
```

The same happens when I try to install the master branch of the package with GAP 4.10.2.

(The installation of the master branch version of the package with the master branch of GAP works.
Is the package meataxe64 really expected to work with GAP 4.10?)

P.S.:
The installation instructions in `README.md` should say `with-gaproot` not `with-gap-root`.

**Comment by olexandr-konovalov** [comment]
@ThomasBreuer Thanks for pointing out - it is known to not to work with GAP 4.10.2, so dependencies must be updated (to 4.11? - needs checking). It's known to work under GAP master, see e.g. this demo from the end of October 2019: https://github.com/OpenDreamKit/gap-demos/blob/master/notebooks-master/Meataxe64%20Demo.ipynb

**Comment by olexandr-konovalov** [comment]
Just to confirm, it works in GAP's stable-4.11 branch, as seen now in #33

**Comment by fingolfin** [comment]
As a matter of fact, this package requires GAP >= 4.11 for several reasons; hence PR #36
